package job.test.forum.models;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.creatorId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Integer creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.createtime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.updatetime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.creatorId
     *
     * @return the value of topic.creatorId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Integer getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.creatorId
     *
     * @param creatorid the value for topic.creatorId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.createtime
     *
     * @return the value of topic.createtime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.createtime
     *
     * @param createtime the value for topic.createtime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.updatetime
     *
     * @return the value of topic.updatetime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.updatetime
     *
     * @param updatetime the value for topic.updatetime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}