package job.test.forum.models;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.topicId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.creatorId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Integer creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.createtime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.updatetime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.topicId
     *
     * @return the value of post.topicId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.topicId
     *
     * @param topicid the value for post.topicId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.creatorId
     *
     * @return the value of post.creatorId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Integer getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.creatorId
     *
     * @param creatorid the value for post.creatorId
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.createtime
     *
     * @return the value of post.createtime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.createtime
     *
     * @param createtime the value for post.createtime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.updatetime
     *
     * @return the value of post.updatetime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.updatetime
     *
     * @param updatetime the value for post.updatetime
     *
     * @mbggenerated Tue Oct 25 20:45:21 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}